### ISSUE TITLE
Dependencies gradle file with full dependency definitions

### ISSUE THREAD

**Issue by lemonboston** [dmfs/ContentPal#113]
In order to manage and update dependencies easier, as a developer, I want a `.gradle` file where the full dependency definitions (org, group, artifact, version) are set to variables which can be used in module `build.gradle` files.
---
So instead of this in a build.gradle file:
```groovy
dependencies {
    compile 'com.android.support:support-annotations:' + SUPPORT_LIBRARY_VERSION
    compile 'org.dmfs:iterators:' + JEMS_VERSION
    compile 'org.dmfs:optional:' + JEMS_VERSION
    compile 'org.dmfs:essentials:' + JEMS_VERSION
    compile project(':contentpal-api')

    testCompile 'junit:junit:' + JUNIT_VERSION
    testCompile 'org.mockito:mockito-core:' + MOCKITO_VERSION
    testCompile 'org.robolectric:robolectric:' + ROBOLECTRIC_VERSION
    testCompile 'org.dmfs:optional-testing:' + JEMS_VERSION
    testCompile project(':contentpal-testing')
}
```
we could write this:
```groovy
dependencies {
    compile deps.support_annotations
    compile deps.dmfs_iterators
    compile deps.dmfs_optional
    compile deps.dmfs_essentials
    compile project(':contentpal-api')

    testCompile deps.junit
    testCompile deps.mockito
    testCompile deps.roboelectric
    testCompile deps.dmfs_optional_testing
    testCompile project(':contentpal-testing')
}
```
This could help in two ways:
- easy to add new dependency which is already used in the project with code completion, no need to copy-paste from other file
- easy replacement of artifact name if needed
One use-case is switching between maven and jitpack when there is parallel development, it can come useful often to use the latest version with jitpack. Even if we didn't want that in master and wait for a release, it is useful during development.
Something like this could be part of the gradle file:
```
def jemsGroup = `org.dmfs`
...
...iterators = jemsGroup + 'iterators' + jemsVersion
..
```
and then we just have to update `jemsGroup` to 'com.github.dmfs.jems' to switch to jitpack and it would update alll module's all jems dependencies.

The same thing could be done in jems project as well.

What do you think?

**Comment by lemonboston** [comment]
Just saw that using gradle file to hold the common properties is a suggested way in official docs as well:
https://developer.android.com/studio/build/index.html (Configure project-wide properties)

**Comment by dmfs** [comment]
ok let's give this a try.

**Comment by lemonboston** [comment]
I've just read this post today:
http://alexfu.github.io/android/2017/11/07/experimenting-with-gradle-dependencies.html
Amazing that he mentions the same exact naming (`deps.x`)..  but the interesting is that he moves it one step forward, although I think it's better not to do that and keep the individual dependencies.

I'd like to suggest that if the `ext.deps` version disables the IDE hint about newer available versions, then we add the gradle plugin that checks them, and possibly add to the default build, so at least we see them from time to time:
https://github.com/ben-manes/gradle-versions-plugin
What do you think?

**Comment by dmfs** [comment]
First let's see if we can get the hints to work without an additional plugin.

**Comment by lemonboston** [comment]
Ok
