### ISSUE TITLE
Consider dropping OperationsBatch

### ISSUE THREAD

**Issue by dmfs** [dmfs/ContentPal#130]
Does it really still make sense to have a dedicated interface for this?

The original `OperationsBatch` had more methods like `size()` and `isEmpty()`. After the redesign these methods have been removed and this it really just an alias to `Iterable<Operation<?>>`. If we ditch `OperationsBatch` and replace it by `Iterable<Operation<?>>` we save a lot of code and can use all the goodies we already have for `Iterable`s.

The only reason to keep this would be for semantics. I.e. to express that all the `Operation`s will be executed in an atomic transaction. But this is not necessarily true if operations within a batch have yield points.

**Comment by lemonboston** [comment]
It feels like that you've answered this already, it makes sense for me, too, to drop it.

These extending, marker kind of interfaces have this problem of not being able to use them in place of the extended type. Kotlin has type aliases: https://kotlinlang.org/docs/reference/type-aliases.html
which don't actually add a new type, just an alias name for it.
Not sure if that was a good practice, but with that we could use `OperationsBatch` as name in place of `Iterable<Operation>`, while it would be still in effect an `Iterable<Operation>`, so the decorators could be applied.

**Comment by dmfs** [comment]
Right, let's do this.
