### ISSUE TITLE
`Projection` type

### ISSUE THREAD

**Issue by dmfs** [dmfs/ContentPal#134]
In order to create projections more easily, for instance by composing smaller projections, I want a `Projection` type which serves as a factory.
---

proposed interface:
```java
public interface Projection
{
    Iterable<String> columns();
}
```

Conversion to an array would be done by a `Single<String[]>`:

```java
String[] projection = new ProjectionArray(new Composite(projection1, projection2)).value();
```

The `Single` might not be the best idea, since the resulting array is mutable (which could be a problem when using `Frozen` and someone modifies the elements.

Another idea would be to let `Projection` return the array directly (instead of an `Iterable`).

Also, `Projection` could offer a method to get the column index of a specific column. Not sure if that would be more efficient than `Cursor.getColumnIndex(String)` though.

Here is another, builder-style version:
```java
public interface Projection
{
     Projection withColumns(Projection columns);
     int columnIndex(String col);
     String[] toArray();
}
```

To be used like this: 
```java
String[] projection = new ArrayProjection(col1, col2).withColumns(projection2).toArray();
```

**Comment by lemonboston** [comment]
Would that `int columnIndex(String col)` only be used in current `QueryRowSet`, instead of `cursor.getColumnNames() ....`  part? If yes, then isn't it unnecessary to put it on the interface?

**Comment by dmfs** [comment]
Right, I guess we don't need that.
