### ISSUE TITLE
Rework `RowDataSnapshot` interface

### ISSUE THREAD

**Issue by dmfs** [dmfs/ContentPal#136]
The `RowDataSnapshot` interface has turned out to be quite inconvenient to use. We need to reconsider the methods.

**Comment by lemonboston** [comment]
An alternative to this is to use these 2 classes the way we started it in OpenTasks:

```java
final class OptionalRowCharData<T, R> extends DelegatingOptional<R>
{
    public OptionalRowCharData(@NonNull RowDataSnapshot<T> rowDataSnapshot,
                               @NonNull String column,
                               @NonNull Function<CharSequence, R> mapFunction)
    {
        super(new Mapped<>(mapFunction, rowDataSnapshot.charData(column)));
    }
}

final class RowCharData<T, R> implements Single<R>
{
    private final RowDataSnapshot<T> mRowDataSnapshot;
    private final String mColumn;
    private final Function<CharSequence, R> mMapFunction;


    public RowCharData(@NonNull RowDataSnapshot<T> rowDataSnapshot,
                       @NonNull String column,
                       @NonNull Function<CharSequence, R> mapFunction)
    {
        mRowDataSnapshot = rowDataSnapshot;
        mColumn = column;
        mMapFunction = mapFunction;
    }


    @Override
    public R value()
    {
        return mMapFunction.apply(mRowDataSnapshot.charData(mColumn).value());
    }
}
```
plus `Function` classes for the type conversions.

I don't have a clear opinion on this atm. If we consider lazy evaluation to be benefitiall than I guess using these 2 classes may be better, because they also allow for not having to call into `RowDataSnapshot` eagerly.
Names could be changed of course.
For `CharSequence` return types there could be 2 extra class (or alternatively using `IdentityFunction` in secondary ctor as you mentioned)

**Comment by lemonboston** [comment]
> using these 2 classes may be better, because they also allow for not having to call into RowDataSnapshot eagerly

Don't mind this, I realized that we probably declare classes for each field anyway, so it will be lazy regardless of `RowDataSnapshot` interface.

---

So if we make this type more convenient to use, then I think we could just go for adding methods for all the common types to the interface. And there could be an adapter between the current `RowDataSnapshot` - which could be renamed to something else - and between this new convenient type:
```java
public interface RowDataSnapshot<T> extends Iterable<String>
{
    Optional<CharSequence> charData(String key);

    Optional<String> stringData(String key); // just in case we need String in client code

    Optional<Integer> intData(String key);

    Optional<Long> longData(String key);

    Optional<Float> floatData(String key);

    Optional<Double> doubleData(String key);

    Optional<Boolean> booleanData(String key);

    Optional<T> mappedData(String key, Function<CharSequence, T> mapFunction);

    Optional<byte[]> byteData(String key);
}
```
This would certainly be more convenient to use. 
Using 2 types would allow for both keeping design good and simple in `ContentPal` internals, while also having convenient usage on client side.
What do you think?

**Comment by dmfs** [comment]
Oh no, all these methods look like a really bad idea. How about just this:
```java
public interface RowDataSnapshot<T> extends Iterable<String>
{
    <Type> Optional<Type> data(String key, Function<CharSequence, Type> mapFunction);

    Optional<byte[]> byteData(String key);
}
```
If you need a `CharSequence` you'd provide the `IdentityFunction`. That looks like a minimal and still somewhat convenient interface at the same time.

Optionally we probably could use `String` right away (instead of `CharSequence`). We get a `String` when we read the `Cursor` anyway. Currently I can't think of any use case when the data would not be read from a `Cursor`.

Also, I'm not entirely sure if we need to extend `Iterable`.

**Comment by dmfs** [comment]
Actually extending `Iterable` can be useful when we want to derive `RowData` from a `RowDataSnapshot`. A use case would be copying database rows.

**Comment by lemonboston** [comment]
Yeah, I get that these big convenience interfaces don't really fit into proper OOP.
This last one looks good to me, too, with the `String` function argument. With Java 8 we will be able to use method references for the trivial conversions, like:
```java
Optional<Integer> optInt = new RowDataSnapshotImpl().data("key", Integer::valueOf);
```

**Comment by dmfs** [comment]
Ok let's do this then:
```java
public interface RowDataSnapshot<T> extends Iterable<String>
{
    <Type> Optional<Type> data(String key, Function<String, Type> mapFunction);

    Optional<byte[]> byteData(String key);
}
```
