### ISSUE TITLE
Common conversion functions

### ISSUE THREAD

**Issue by lemonboston** [dmfs/ContentPal#143]
Conversion functions that are not general enough to go into jems can come here.

Like 
`Duration.parse(String)`
`AddDurationBiFunction`
`String -> bolts.Color` // if Color is imported here

**Comment by lemonboston** [comment]
Just realized that neither `DateTime` nor `Color` is imported in `contentpal` module, so these will probably just stay in OpenTaskPal. Or if you have a better idea where to put them, please let me know.
Closing this.

**Comment by dmfs** [comment]
Leave it in OpenTasksPal for now. We'll probably create a new module somewhere when we need them in CalendarPal as well.
