### ISSUE TITLE
Allow CalendarRowData classes for Composite pattern

### ISSUE THREAD

**Issue by dmfs** [dmfs/ContentPal#159]
In order to use `CalendarRowData` more easily, I want it to support the `Composite` usage pattern.
---

At present you create `CalendarRowData` with a decorator pattern like so:
```java
RowData<Calendar> data = new Synced(new Visible(new Owned("me@example.com", new CalendarData("Personal"))));
```
In most cases it might be easier to use it like so:
```java
RowData<Calendar> data = new Composite<>(
    new Synced(),
    new Visible(),
    new Owned("me@example.com"),
    new Named("Personal"));
```
The question is, do we support both or can we ditch the first pattern in this case? In ContactsPal we currently have postal data and organization data supporting both. We could ditch the decorator pattern for them as well.

**Comment by lemonboston** [comment]
It feels like a clearer approach for me to only support one type of usage then. So ditching the decorator. Supporting both adds a bit of ambiguity which one to use, also a bit more code to write and maintain.

**Comment by dmfs** [comment]
Right, I'll create separate issues for the ContentPal classes.
