### ISSUE TITLE
minSdkVersion is not the same among the modules

### ISSUE THREAD

**Issue by lemonboston** [dmfs/ContentPal#55]
@dmfs Is this on purpose?

calendarpal 14
contactspal 11
contentpal 11

(testing module will have 11)

**Comment by dmfs** [comment]
ContentPal and ContactsPal can work from SDK level 11+, but CalendarPal doesn't work with SDK Level <14 because the CalendarContract is not public in earlier SDK versions.
So yes, this is on purpose.

**Comment by lemonboston** [comment]
I see, thanks.
