### ISSUE TITLE
Typo in contenttestpal package name

### ISSUE THREAD

**Issue by lemonboston** [dmfs/ContentPal#72]

**Comment by lemonboston** [comment]
@dmfs By the way, what do you think about removing `android` from the package names?
`org.dmfs.android.contentpal` -> `org.dmfs.contentpal`
Just to keep them a bit shorter.

**Comment by dmfs** [comment]
I'd like to have `android` in all packages which are android specific. Just to make it clear that this won't run anywhere else.
